server:
  port: 8082

spring:
  application:
    name: point-service
  datasource:
    url: jdbc:mysql://180.210.78.177:3307/smartcane?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: smartcane
    password: Smartcane1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: smartcane
    default-schema: smartcane
    baseline-on-migrate: true   # ← 최초 1회만
    baseline-version: 0

logging:
  level:
    org.flywaydb: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /docs           # 스웨거 UI 접속 경로: http://localhost:8082/docs
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    doc-expansion: none
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
