server:
  port: 8082

spring:
  application:
    name: point-service
  datasource:
    url: jdbc:mysql://smartcane-point.cl6w2uwm6s0b.ap-southeast-2.rds.amazonaws.com:3306/pointdb?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: Smartcane1!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000
      keepalive-time: 300000
      idle-timeout: 600000
      max-lifetime: 180000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: smartcane
    default-schema: smartcane
  # baseline-* 제거 (이미 완료됨)


logging:
  level:
    org.flywaydb: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /docs           # 스웨거 UI 접속 경로: http://localhost:8082/docs
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    doc-expansion: none
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
